spring.application.name=dataox
spring.datasource.url=jdbc:postgresql://localhost:5432/dataox
spring.datasource.username=postgres
spring.datasource.password=3243
spring.datasource.driver-class-name=org.postgresql.Driver